--
-- Structure de la table `COURSES`
--

CREATE TABLE `COURSES` (
  `NO_COURSE` int(11) NOT NULL,
  `VESTIAIRE` time DEFAULT NULL,
  `REMISE` time DEFAULT NULL,
  `DEPART` time DEFAULT NULL,
  `FIN` time DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Index pour la table `COURSES`
--
ALTER TABLE `COURSES`
  ADD PRIMARY KEY (`NO_COURSE`);

--
-- Structure de la table `PARTICIPANTS`
--

CREATE TABLE `PARTICIPANTS` (
  `NO_PARTICIPANT` bigint(4) NOT NULL,
  `ID_CLASSE` varchar(10) NOT NULL,
  `NOM` varchar(128) DEFAULT NULL,
  `PRENOM` varchar(128) DEFAULT NULL,
  `INSCRIT` char(1) DEFAULT NULL,
  `AUTORISATION` char(1) DEFAULT NULL,
  `DROIT_IMAGE` char(1) DEFAULT NULL,
  `DOSSIER` char(32) DEFAULT NULL,
  `DOSSARD` bigint(4) DEFAULT NULL,
  `COULEUR` varchar(15) DEFAULT NULL,
  `KMPARCOURUS` bigint(4) DEFAULT NULL,
  `PROMESSE` double(5,2) DEFAULT NULL,
  `MONTANT` double(5,2) DEFAULT NULL,
  `MTREEL` double(5,2) DEFAULT NULL,
  `LOGIN_ELEVE` varchar(128) DEFAULT NULL,
  `MDP_ELEVE` varchar(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Index pour la table `PARTICIPANTS`
--
ALTER TABLE `PARTICIPANTS`
  ADD PRIMARY KEY (`NO_PARTICIPANT`);

--
-- AUTO_INCREMENT pour la table `PARTICIPANTS`
--
ALTER TABLE `PARTICIPANTS`
  MODIFY `NO_PARTICIPANT` bigint(4) NOT NULL AUTO_INCREMENT;


--
-- Structure de la table `PROFESSEURS`
--

CREATE TABLE `PROFESSEURS` (
  `LOGIN` varchar(32) NOT NULL,
  `MOT_DE_PASSE` varchar(40) DEFAULT NULL,
  `NOM_PROFESSEUR` varchar(128) DEFAULT NULL,
  `PRENOM_PROFESSEUR` varchar(128) DEFAULT NULL,
  `MATIERE` varchar(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Index pour la table `PROFESSEURS`
--
ALTER TABLE `PROFESSEURS`
  ADD PRIMARY KEY (`LOGIN`);



CREATE TABLE `CLASSE` (
  `ID_CLASSE` varchar(10) NOT NULL,
  `NO_COURSE` int(11) DEFAULT NULL,
  `LOGIN` varchar(32) NOT NULL,
  `NOM_CLASSE` varchar(128) DEFAULT NULL,
  `COURSE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Index pour la table `CLASSE`
--
ALTER TABLE `CLASSE`
  ADD PRIMARY KEY (`ID_CLASSE`),
  ADD KEY `classe_ibfk_2` (`LOGIN`),
  ADD KEY `classe_ibfk_1` (`NO_COURSE`);

--
-- Contraintes pour la table `CLASSE`
--
ALTER TABLE `CLASSE`
  ADD CONSTRAINT `classe_ibfk_1` FOREIGN KEY (`NO_COURSE`) REFERENCES `COURSES` (`NO_COURSE`),
  ADD CONSTRAINT `classe_ibfk_2` FOREIGN KEY (`LOGIN`) REFERENCES `PROFESSEURS` (`LOGIN`);